services:
  backend:
    build:
      context: ../../../server
      dockerfile: Dockerfile
    environment:
      - SESSION_SECRET=github-docker-ci-secret-doesnt-matter
    expose:
      - 5000
    networks:
      - app-network

  frontend:
    build:
      context: ../../../frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
