name: Deploy Containers

on:
  push:
    tags:
      - 'v*'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Test images
        working-directory: .github/workflows/deploy-compose
        run: |
          docker compose up --build
          echo waiting 10 sec
          sleep 10
          echo try to reach backend
          curl --retry 3 --retry-delay 5 --fail http://localhost:5000/api/health
          echo trying to reach frontend
          curl --retry 3 --retry-delay 5 --fail http://localhost:80
          docker compose down

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          docker build -t vizigr0u/anavlad-frontend:${GITHUB_REF_NAME} .

      - name: Build Backend
        working-directory: ./backend
        run: |
          docker build -t vizigr0u/anavlad-backend:${GITHUB_REF_NAME} .

      - name: Push Docker Images
        run: |
          docker push vizigr0u/anavlad-backend:${GITHUB_REF_NAME}
          docker push vizigr0u/anavlad-frontend:${GITHUB_REF_NAME}
