name: Deploy Containers

on:
  push:
    tags:
      - 'v*'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Test Backend
        working-directory: ./server
        run: |
          docker build -t vizigr0u/backend:${GITHUB_REF_NAME} .
          docker run -d -p 3000:3000 --name backend-test vizigr0u/backend:${GITHUB_REF_NAME}
          sleep 10  # Wait for server to start
          curl --retry 3 --retry-delay 5 --fail http://localhost:3000/health-check
          docker stop backend-test

      - name: Build and Test Frontend
        working-directory: ./frontend
        run: |
          docker build -t vizigr0u/frontend:${GITHUB_REF_NAME} .
          docker run -d -p 80:80 --name frontend-test vizigr0u/frontend:${GITHUB_REF_NAME}
          sleep 5
          curl --retry 3 --retry-delay 5 --fail http://localhost:80
          docker stop frontend-test

      - name: Push Docker Images
        run: |
          docker push vizigr0u/backend:${GITHUB_REF_NAME}
          docker push vizigr0u/frontend:${GITHUB_REF_NAME}
